FROM ruby:3.2.3

# 必要なパッケージのインストール
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    vim

WORKDIR /app

COPY Gemfile Gemfile.lock /app/
RUN gem install foreman
RUN bundle install

ADD . /app