FROM ruby:3.2.3

WORKDIR /app

COPY Gemfile Gemfile.lock /app/

RUN bundle install

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3003

CMD ["rails", "server", "-b", "0.0.0.0"]