default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("MYSQL_DB") { '' } %>
  username: <%= ENV.fetch("MYSQL_USER") { '' } %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { '' } %>
  host: db

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { '' } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { '_test' } %>_test

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>